In [2]:
import pandas as pd
import numpy as np

In [3]:
df= pd.read_csv("Downloads/SPAM-HAM/dataset.csv")
df

v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [4]:
df.shape

(5572, 5)

## Data Cleaning

In [6]:
df.info

<bound method DataFrame.info of         v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN

In [7]:
df.drop(columns=['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], inplace=True)
df.rename(columns={'v1': 'class', 'v2': 'text'}, inplace=True)
df

class                                               text
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [8]:
from sklearn.preprocessing import LabelEncoder
encoder= LabelEncoder()
df['class']=encoder.fit_transform(df['class'])

In [9]:
df.isnull().sum()

class    0
text     0
dtype: int64

In [10]:
df=df.drop_duplicates(keep='first')
df

class                                               text
0         0  Go until jurong point, crazy.. Available only ...
1         0                      Ok lar... Joking wif u oni...
2         1  Free entry in 2 a wkly comp to win FA Cup fina...
3         0  U dun say so early hor... U c already then say...
4         0  Nah I don't think he goes to usf, he lives aro...
...     ...                                                ...
5567      1  This is the 2nd time we have tried 2 contact u...
5568      0              Will Ì_ b going to esplanade fr home?
5569      0  Pity, * was in mood for that. So...any other s...
5570      0  The guy did some bitching but I acted like i'd...
5571      0                         Rofl. Its true to its name

[5169 rows x 2 columns]

## EDA

In [12]:
df['class'].value_counts()

class
0    4516
1     653
Name: count, dtype: int64

In [13]:
!pip install nltk

In [14]:
import nltk

In [15]:
df['noOfChar']= df['text'].apply(len)
df

C:\Users\Anushka\AppData\Local\Temp\ipykernel_10280\981917940.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['noOfChar']= df['text'].apply(len)


class                                               text  noOfChar
0         0  Go until jurong point, crazy.. Available only ...       111
1         0                      Ok lar... Joking wif u oni...        29
2         1  Free entry in 2 a wkly comp to win FA Cup fina...       155
3         0  U dun say so early hor... U c already then say...        49
4         0  Nah I don't think he goes to usf, he lives aro...        61
...     ...                                                ...       ...
5567      1  This is the 2nd time we have tried 2 contact u...       161
5568      0              Will Ì_ b going to esplanade fr home?        37
5569      0  Pity, * was in mood for that. So...any other s...        57
5570      0  The guy did some bitching but I acted like i'd...       125
5571      0                         Rofl. Its true to its name        26

[5169 rows x 3 columns]

In [16]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Anushka\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [17]:
df['noOfWords']=df['text'].apply(lambda x: len(nltk.word_tokenize(x)))
df['noOfSent']=df['text'].apply(lambda x: len(nltk.sent_tokenize(x)))
df

C:\Users\Anushka\AppData\Local\Temp\ipykernel_10280\994774840.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['noOfWords']=df['text'].apply(lambda x: len(nltk.word_tokenize(x)))
C:\Users\Anushka\AppData\Local\Temp\ipykernel_10280\994774840.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['noOfSent']=df['text'].apply(lambda x: len(nltk.sent_tokenize(x)))


class                                               text  noOfChar  \
0         0  Go until jurong point, crazy.. Available only ...       111   
1         0                      Ok lar... Joking wif u oni...        29   
2         1  Free entry in 2 a wkly comp to win FA Cup fina...       155   
3         0  U dun say so early hor... U c already then say...        49   
4         0  Nah I don't think he goes to usf, he lives aro...        61   
...     ...                                                ...       ...   
5567      1  This is the 2nd time we have tried 2 contact u...       161   
5568      0              Will Ì_ b going to esplanade fr home?        37   
5569      0  Pity, * was in mood for that. So...any other s...        57   
5570      0  The guy did some bitching but I acted like i'd...       125   
5571      0                         Rofl. Its true to its name        26   

      noOfWords  noOfSent  
0            24         2  
1             8         2  
2            37         2  
3            13         1  
4            15         1  
...         ...       ...  
5567         35         4  
5568          9         1  
5569         15         2  
5570         27         1  
5571          7         2  

[5169 rows x 5 columns]

In [18]:
df[['noOfChar'	,'noOfWords',	'noOfSent']].describe()

noOfChar    noOfWords     noOfSent
count  5169.000000  5169.000000  5169.000000
mean     78.977945    18.455794     1.965564
std      58.236293    13.324758     1.448541
min       2.000000     1.000000     1.000000
25%      36.000000     9.000000     1.000000
50%      60.000000    15.000000     1.000000
75%     117.000000    26.000000     2.000000
max     910.000000   220.000000    38.000000

In [19]:
#ham
df[df['class']==0][['noOfChar'	,'noOfWords',	'noOfSent']].describe()

noOfChar    noOfWords     noOfSent
count  4516.000000  4516.000000  4516.000000
mean     70.459256    17.123782     1.820195
std      56.358207    13.493970     1.383657
min       2.000000     1.000000     1.000000
25%      34.000000     8.000000     1.000000
50%      52.000000    13.000000     1.000000
75%      90.000000    22.000000     2.000000
max     910.000000   220.000000    38.000000

In [20]:
#ham
df[df['class']==1][['noOfChar'	,'noOfWords',	'noOfSent']].describe()

noOfChar   noOfWords    noOfSent
count  653.000000  653.000000  653.000000
mean   137.891271   27.667688    2.970904
std     30.137753    7.008418    1.488425
min     13.000000    2.000000    1.000000
25%    132.000000   25.000000    2.000000
50%    149.000000   29.000000    3.000000
75%    157.000000   32.000000    4.000000
max    224.000000   46.000000    9.000000

## Data Preprocessing

In [22]:
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Anushka\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [23]:
from nltk.stem.porter import PorterStemmer
ps= PorterStemmer()
import string

In [24]:
def transform_text(text):
    
    #convert to lower case
    text=text.lower()
    
    #split into tokens, into array of sorts
    text=nltk.word_tokenize(text)
    
    #make a list of alphanumeric tokens (no special characters)
    x=[]
    for i in text:
        if i.isalnum():
            x.append(i)
    text=x[:]
    
    #remove any and all stopwords
    x.clear()
    for i in text:
        if i not in stopwords.words('english') and i not in string.punctuation:
            x.append(i)
    text=x[:]
    
    #stemming words
    x.clear()
    for i in text:
        x.append(ps.stem(i))
    
    return " ".join(x)

In [25]:
#example of the transformation
transform_text("I loved the YT lectures on ML!")

'love yt lectur ml'

In [116]:
df.loc[:, "transformedText"] = df["text"].apply(transform_text)

In [117]:
df

class                                               text  noOfChar  \
0         0  Go until jurong point, crazy.. Available only ...       111   
1         0                      Ok lar... Joking wif u oni...        29   
2         1  Free entry in 2 a wkly comp to win FA Cup fina...       155   
3         0  U dun say so early hor... U c already then say...        49   
4         0  Nah I don't think he goes to usf, he lives aro...        61   
...     ...                                                ...       ...   
5567      1  This is the 2nd time we have tried 2 contact u...       161   
5568      0              Will Ì_ b going to esplanade fr home?        37   
5569      0  Pity, * was in mood for that. So...any other s...        57   
5570      0  The guy did some bitching but I acted like i'd...       125   
5571      0                         Rofl. Its true to its name        26   

      noOfWords  noOfSent                                    transformedText  
0            24         2  go jurong point crazi avail bugi n great world...  
1             8         2                              ok lar joke wif u oni  
2            37         2  free entri 2 wkli comp win fa cup final tkt 21...  
3            13         1                u dun say earli hor u c alreadi say  
4            15         1               nah think goe usf live around though  
...         ...       ...                                                ...  
5567         35         4  2nd time tri 2 contact u pound prize 2 claim e...  
5568          9         1                              b go esplanad fr home  
5569         15         2                                  piti mood suggest  
5570         27         1  guy bitch act like interest buy someth els nex...  
5571          7         2                                     rofl true name  

[5169 rows x 6 columns]

In [118]:
spamCount=[]
for msg in df[df['class']==1]['transformedText'].tolist():
    for word in msg.split():
        spamCount.append(word)

len(spamCount)

9939

In [119]:
hamCount=[]
for msg in df[df['class']==0]['transformedText'].tolist():
    for word in msg.split():
        hamCount.append(word)

len(hamCount)

35404

## Naive Bayes Model

In [121]:
from sklearn.feature_extraction.text import CountVectorizer
cv= CountVectorizer()

In [122]:
X1= cv.fit_transform(df['transformedText']).toarray()

In [123]:
X1.shape

(5169, 6708)

In [124]:
Y1= df['class'].values
Y1

array([0, 0, 1, ..., 0, 0, 0])

In [125]:
from sklearn.model_selection import train_test_split

In [126]:
X1_train, X1_test, Y1_train, Y1_test= train_test_split(X1,Y1, test_size=0.2, random_state=2)

In [127]:
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score
gNB = GaussianNB()
mNB = MultinomialNB()
bNB = BernoulliNB()

In [128]:
gNB.fit(X1_train, Y1_train)
predGNB= gNB.predict(X1_test)
print(accuracy_score(Y1_test,predGNB))
print(confusion_matrix(Y1_test,predGNB))
print(precision_score(Y1_test,predGNB))

0.8800773694390716
[[792 104]
 [ 20 118]]
0.5315315315315315


In [129]:
mNB.fit(X1_train, Y1_train)
predMNB= mNB.predict(X1_test)
print(accuracy_score(Y1_test,predMNB))
print(confusion_matrix(Y1_test,predMNB))
print(precision_score(Y1_test,predMNB))

0.9642166344294004
[[871  25]
 [ 12 126]]
0.8344370860927153


In [130]:
bNB.fit(X1_train, Y1_train)
predBNB= bNB.predict(X1_test)
print(accuracy_score(Y1_test,predBNB))
print(confusion_matrix(Y1_test,predBNB))
print(precision_score(Y1_test,predBNB))

0.9700193423597679
[[893   3]
 [ 28 110]]
0.9734513274336283


## Using Naive Bayes along with a TF-IDF Score

In [132]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_features=3000)

In [218]:
X=  tfidf.fit_transform(df['transformedText']).toarray()

In [183]:
X.shape

(5169, 3000)

In [184]:
y = df['class'].values

In [185]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [186]:
gNB.fit(X_train,y_train)
y_pred1 = gNB.predict(X_test)
print(accuracy_score(y_test,y_pred1))
print(confusion_matrix(y_test,y_pred1))
print(precision_score(y_test,y_pred1))

0.8694390715667312
[[788 108]
 [ 27 111]]
0.5068493150684932


In [187]:
mNB.fit(X_train,y_train)
y_pred2 = mNB.predict(X_test)
print(accuracy_score(y_test,y_pred2))
print(confusion_matrix(y_test,y_pred2))
print(precision_score(y_test,y_pred2))

0.9709864603481625
[[896   0]
 [ 30 108]]
1.0


In [188]:
bNB.fit(X_train,y_train)
y_pred3 = bNB.predict(X_test)
print(accuracy_score(y_test,y_pred3))
print(confusion_matrix(y_test,y_pred3))
print(precision_score(y_test,y_pred3))

0.9835589941972921
[[895   1]
 [ 16 122]]
0.991869918699187


## Other ML Algorithms

In [190]:
from sklearn.linear_model import LogisticRegression
lrc = LogisticRegression(solver='liblinear', penalty='l1')

from sklearn.svm import SVC
svc = SVC(kernel='sigmoid', gamma=1.0)

from sklearn.naive_bayes import MultinomialNB
mnb = MultinomialNB()

from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(max_depth=5)

from sklearn.neighbors import KNeighborsClassifier
knc = KNeighborsClassifier()

from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=50, random_state=2)

from sklearn.ensemble import AdaBoostClassifier
abc = AdaBoostClassifier(n_estimators=50, algorithm='SAMME', random_state=2)


#from sklearn.ensemble import BaggingClassifier
#bc = BaggingClassifier(n_estimators=50, random_state=2)

#from sklearn.ensemble import ExtraTreesClassifier
#etc = ExtraTreesClassifier(n_estimators=50, random_state=2)

#from sklearn.ensemble import GradientBoostingClassifier
#gbdt = GradientBoostingClassifier(n_estimators=50,random_state=2)

In [191]:
clfs = {
    'SVC' : svc,
    'KN' : knc, 
    'NB': mnb, 
    'DT': dtc, 
    'LR': lrc, 
    'RF': rfc, 
    'AdaBoost': abc, 
    #'BgC': bc, 
    #'ETC': etc,
    #'GBDT':gbdt,
}

In [192]:
def train_classifier(clf,X_train,y_train,X_test,y_test):
    clf.fit(X_train,y_train)
    y_pred = clf.predict(X_test)
    accuracy = accuracy_score(y_test,y_pred)
    precision = precision_score(y_test,y_pred)
    
    return accuracy,precision

In [193]:
accuracy_scores = []
precision_scores = []

for name, clf in clfs.items():
    print(f"Training {name}")
    current_accuracy, current_precision = train_classifier(clf, X_train, y_train, X_test, y_test)
    accuracy_scores.append(current_accuracy)
    precision_scores.append(current_precision)
    print(f"Finished {name}")

performance_df = pd.DataFrame({'Algorithm':clfs.keys(),'Accuracy':accuracy_scores,'Precision':precision_scores}).sort_values('Precision',ascending=False)

Training SVC
Finished SVC
Training KN
Finished KN
Training NB
Finished NB
Training DT
Finished DT
Training LR
Finished LR
Training RF
Finished RF
Training AdaBoost
Finished AdaBoost


In [194]:
performance_df

Algorithm  Accuracy  Precision
1        KN  0.905222   1.000000
2        NB  0.970986   1.000000
5        RF  0.975822   0.982906
0       SVC  0.975822   0.974790
4        LR  0.958414   0.970297
6  AdaBoost  0.924565   0.848837
3        DT  0.927466   0.811881

In [195]:
rfc.fit(X_train,y_train)

RandomForestClassifier(n_estimators=50, random_state=2)

In [224]:
from sklearn.metrics import classification_report
predicted_labels = rfc.predict(X_test)
report = classification_report(y_test, predicted_labels)
print("Classification Report:\n") 
print(report)

Classification Report:

              precision    recall  f1-score   support

           0       0.97      1.00      0.99       896
           1       0.98      0.83      0.90       138

    accuracy                           0.98      1034
   macro avg       0.98      0.92      0.94      1034
weighted avg       0.98      0.98      0.97      1034



### Hence using RF! 

In [197]:
import pickle
pickle.dump(tfidf,open('vectorizer.pkl','wb'))
pickle.dump(rfc,open('model.pkl','wb'))

In [198]:
import joblib

joblib.dump(tfidf, 'vectorizer.joblib')
joblib.dump(rfc, 'model.joblib')

['model.joblib']

AttributeError: 'numpy.ndarray' object has no attribute 'lower'